import type { Metadata } from "next";
import "./globals.css";
import MuiThemeRegistry from "@/theme/ThemeProvider";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <MuiThemeRegistry>
          <nav>
            <div className="max-w-3xl mx-auto p-6 space-y-6">
              <ul className="flex gap-3">
                <li>
                  <Link href={"/"} className="p-2">
                    خانه
                  </Link>
                </li>
                <li>
                  <Link href={"/posts"} className="p-2">
                    مقالات
                  </Link>
                </li>
                <li>
                  <Link href={"/profile"} className="p-2">
                    پروفایل
                  </Link>
                </li>
              </ul>
            </div>
          </nav>
          {children}
        </MuiThemeRegistry>
      </body>
    </html>
  );
}
